{% set version = "0.1.9" %}

package:
  name: "snakestage"
  version: {{ version }} 

source:
  git_rev: v{{ version }}
  git_url: https://github.com/maarten-k/snakestage

build:
  number: 1
  noarch: python

requirements:
  host:
    - python
    - setuptools
  build:
     []
  run:
    - python
    - snakemake-minimal
    - tqdm


about:
  home: https://github.com/maarten-k/snakestage
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "Using a snakemake pipeline taking staging file into account (based on dcache API and SLURM) "

extra:
  recipe-maintainers:
    - maarten-k
  skip-lints:
    - should_be_noarch_python

